-module(erlxml_deserialise_tests).

-include ( "../src/erlxml.hrl" ).
-include ( "test_helper.hrl" ).
-include_lib("eunit/include/eunit.hrl").

% deserialise_1_test() ->
%     {ok, Schema} = erlxml:build_schema_state({file, ?MOCK1XSD}),
%     Res = erlxml_deserialise:deserialise({file, ?MOCK1XML}, Schema),
%     ?assertMatch(?MOCK1MAPRES, Res).

% deserialise_2_test() ->
%     {ok, Schema} = erlxml:build_schema_state({file, ?MOCK2XSD}),
%     Res = erlxml_deserialise:deserialise({file, ?MOCK2XML}, Schema),
%     ?assertMatch(?MOCK2MAPRES, Res).

% deserialise_from_string_test() ->
%     {ok, Xsd} = file:read_file(?MOCK2XSD),
%     {ok, Schema} = erlxml:build_schema_state({binary, Xsd}),
%     {ok, Xml} = file:read_file(?MOCK2XML),
%     Res = erlxml_deserialise:deserialise(Xml, Schema),
%     ?assertMatch(?MOCK2MAPRES, Res).


%
% REFACTOR BELOW!!
%
deserialise_soap_test() ->
    %
    %   IMPLEMENTATION TO MOVE TO ACTUAL LIB!!!!!
    %
    {ok, Schema} = erlxml:build_schemas_state({file, "mock"}),
    Res = erlxml_deserialise:deserialise({file, ?MOCKBID_RES_XML}, Schema),
    ?assertMatch(#{'MakeBookingWithQuoteResponse' :=
                       #{'MakeBookingWithQuoteResult' :=
                             #{'AccountID' := <<"RFCACC">>,
                               'CardAuth' := <<"1000">>,'Errors' := #{},
                               'RecordType' := <<"BR">>,
                               'RentalDuration' := <<"5">>,
                               'ReservationLines' :=
                                   #{'ReservationLine' :=
                                         #{'ResLineChrg' := <<"0.00">>,
                                           'ResLineChrgUnit' := #{},
                                           'ResLineCode' := <<"C">>,
                                           'ResLineDesc1' :=
                                               <<"Fuel - Vehicle will be refueled at Renters cost">>,
                                           'ResLineDesc2' := #{},
                                           'ResLineNil' := #{},
                                           'ResLineUnitChrg' := <<"0.00">>}},
                               'ReservationNumber' := <<"852852">>,
                               'VoucherNo' := <<"852858296">>}},
                   <<"_xattributes">> :=
                       [{xmlns,<<"http://www.budget.co.za">>}]}, Res).


serialise2_test() ->
    {ok, Schema} = erlxml:build_schemas_state({file, "mock"}),
    Res = erlxml_serialise:serialise(
                             #{'MakeBookingWithQuoteResponse' =>
                                   #{'MakeBookingWithQuoteResult' =>
                                         #{'AccountID' => <<"DISCAG">>,
                                           'CardAuth' => <<"4000">>,
                                           'Errors' => #{},
                                           'RecordType' => <<"BR">>,
                                           'RentalDuration' => 5,
                                           'ReservationLines' =>
                                               #{'ReservationLine' =>
                                                     #{'ResLineChrg' =>
                                                           <<"0.00">>,
                                                       'ResLineChrgUnit' =>
                                                           #{},
                                                       'ResLineCode' =>
                                                           <<"C">>,
                                                       'ResLineDesc1' =>
                                                           <<"Fuel - Vehicle will be refueled at Renters cost">>,
                                                       'ResLineDesc2' => #{},
                                                       'ResLineNil' => #{},
                                                       'ResLineUnitChrg' =>
                                                           <<"0.00">>}},
                                           'ReservationNumber' =>
                                               <<"4170577">>,
                                           'VoucherNo' => <<"15095327">>}},
                                <<"_xattributes">> =>
                                   [{xmlns,<<"http://www.budget.co.za">>}]
                    
                }, Schema),
    ?assertMatch({ok, <<"<?xml version=\"1.0\"?><MakeBookingWithQuoteResponse xmlns=\"http://www.budget.co.za\"><MakeBookingWithQuoteResult><AccountID>DISCAG</AccountID><RentalDuration>5</RentalDuration><RecordType>BR</RecordType><ReservationNumber>4170577</ReservationNumber><CardAuth>4000</CardAuth><VoucherNo>15095327</VoucherNo><ReservationLines><ReservationLine><ResLineCode>C</ResLineCode><ResLineDesc1>Fuel - Vehicle will be refueled at Renters cost</ResLineDesc1><ResLineUnitChrg>0.00</ResLineUnitChrg><ResLineChrgUnit/><ResLineDesc2/><ResLineChrg>0.00</ResLineChrg><ResLineNil/></ReservationLine></ReservationLines><Errors/></MakeBookingWithQuoteResult></MakeBookingWithQuoteResponse>">>}, Res).


% {xmlElement,'soap:Envelope','soap:Envelope',
%   {"soap","Envelope"},
%   {xmlNamespace,[],
%    [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%     {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%     {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%   [],1,
%   [{xmlAttribute,'xmlns:soap',[],
%     {"xmlns","soap"},
%     [],
%     [{'soap:Envelope',1}],
%     1,[],"http://www.w3.org/2003/05/soap-envelope",false},
%    {xmlAttribute,'xmlns:xsi',[],
%     {"xmlns","xsi"},
%     [],
%     [{'soap:Envelope',1}],
%     2,[],"http://www.w3.org/2001/XMLSchema-instance",false},
%    {xmlAttribute,'xmlns:xsd',[],
%     {"xmlns","xsd"},
%     [],
%     [{'soap:Envelope',1}],
%     3,[],"http://www.w3.org/2001/XMLSchema",false}],
%   [{xmlElement,'soap:Body','soap:Body',
%     {"soap","Body"},
%     {xmlNamespace,[],
%      [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%       {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%       {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%     [{'soap:Envelope',1}],
%     1,[],
%     [{xmlElement,'MakeBookingWithQuoteResponse',
%       'MakeBookingWithQuoteResponse',[],
%       {xmlNamespace,'http://www.budget.co.za',
%        [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%         {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%         {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%       [{'soap:Body',1},{'soap:Envelope',1}],
%       1,
%       [{xmlAttribute,xmlns,[],[],[],
%         [{'MakeBookingWithQuoteResponse',1},
%          {'soap:Body',1},
%          {'soap:Envelope',1}],
%         1,[],"http://www.budget.co.za",false}],
%       [{xmlElement,'MakeBookingWithQuoteResult','MakeBookingWithQuoteResult', 
%         [],
%         {xmlNamespace,'http://www.budget.co.za',
%          [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%           {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%           {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%         [{'MakeBookingWithQuoteResponse',1},
%          {'soap:Body',1},
%          {'soap:Envelope',1}],
%         1,[],
%         [{xmlElement,'AccountID','AccountID',[],
%           {xmlNamespace,'http://www.budget.co.za',
%            [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%             {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%             {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%           [{'MakeBookingWithQuoteResult',1},
%            {'MakeBookingWithQuoteResponse',1},
%            {'soap:Body',1},
%            {'soap:Envelope',1}],
%           1,[],
%           [{xmlText,
%             [{'AccountID',1},
%              {'MakeBookingWithQuoteResult',1},
%              {'MakeBookingWithQuoteResponse',1},
%              {'soap:Body',1},
%              {'soap:Envelope',1}],
%             1,[],"DISCAG",text}],
%           [],"/home/dag-development/Documents/erlang/erlxml",undeclared},
%          {xmlElement,'RecordType','RecordType',[],
%           {xmlNamespace,'http://www.budget.co.za',
%            [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%             {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%             {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%           [{'MakeBookingWithQuoteResult',1},
%            {'MakeBookingWithQuoteResponse',1},
%            {'soap:Body',1},
%            {'soap:Envelope',1}],
%           2,[],
%           [{xmlText,
%             [{'RecordType',2},
%              {'MakeBookingWithQuoteResult',1},
%              {'MakeBookingWithQuoteResponse',1},
%              {'soap:Body',1},
%              {'soap:Envelope',1}],
%             1,[],"BR",text}],
%           [],"/home/dag-development/Documents/erlang/erlxml",undeclared},
%          {xmlElement,'ReservationNumber','ReservationNumber',[],
%           {xmlNamespace,'http://www.budget.co.za',
%            [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%             {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%             {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%           [{'MakeBookingWithQuoteResult',1},
%            {'MakeBookingWithQuoteResponse',1},
%            {'soap:Body',1},
%            {'soap:Envelope',1}],
%           3,[],
%           [{xmlText,
%             [{'ReservationNumber',3},
%              {'MakeBookingWithQuoteResult',1},
%              {'MakeBookingWithQuoteResponse',1},
%              {'soap:Body',1},
%              {'soap:Envelope',1}],
%             1,[],"4170577",text}],
%           [],"/home/dag-development/Documents/erlang/erlxml",undeclared},
%          {xmlElement,'CardAuth','CardAuth',[],
%           {xmlNamespace,'http://www.budget.co.za',
%            [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%             {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%             {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%           [{'MakeBookingWithQuoteResult',1},
%            {'MakeBookingWithQuoteResponse',1},
%            {'soap:Body',1},
%            {'soap:Envelope',1}],
%           4,[],
%           [{xmlText,
%             [{'CardAuth',4},
%              {'MakeBookingWithQuoteResult',1},
%              {'MakeBookingWithQuoteResponse',1},
%              {'soap:Body',1},
%              {'soap:Envelope',1}],
%             1,[],"4000",text}],
%           [],"/home/dag-development/Documents/erlang/erlxml",undeclared},
%          {xmlElement,'VoucherNo','VoucherNo',[],
%           {xmlNamespace,'http://www.budget.co.za',
%            [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%             {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%             {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%           [{'MakeBookingWithQuoteResult',1},
%            {'MakeBookingWithQuoteResponse',1},
%            {'soap:Body',1},
%            {'soap:Envelope',1}],
%           5,[],
%           [{xmlText,
%             [{'VoucherNo',5},
%              {'MakeBookingWithQuoteResult',1},
%              {'MakeBookingWithQuoteResponse',1},
%              {'soap:Body',1},
%              {'soap:Envelope',1}],
%             1,[],"15095327",text}],
%           [],"/home/dag-development/Documents/erlang/erlxml",undeclared},
%          {xmlElement,'ReservationLines','ReservationLines',[],
%           {xmlNamespace,'http://www.budget.co.za',
%            [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%             {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%             {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%           [{'MakeBookingWithQuoteResult',1},
%            {'MakeBookingWithQuoteResponse',1},
%            {'soap:Body',1},
%            {'soap:Envelope',1}],
%           6,[],
%           [{xmlElement,'ReservationLine','ReservationLine',[],
%             {xmlNamespace,'http://www.budget.co.za',
%              [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%               {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%               {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%             [{'ReservationLines',6},
%              {'MakeBookingWithQuoteResult',1},
%              {'MakeBookingWithQuoteResponse',1},
%              {'soap:Body',1},
%              {'soap:Envelope',1}],
%             1,[],
%             [{xmlElement,'ResLineCode','ResLineCode',[],
%               {xmlNamespace,'http://www.budget.co.za',
%                [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%                 {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%                 {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%               [{'ReservationLine',1},
%                {'ReservationLines',6},
%                {'MakeBookingWithQuoteResult',1},
%                {'MakeBookingWithQuoteResponse',1},
%                {'soap:Body',1}, 
%                {'soap:Envelope',1}],
%               1,[],
%               [{xmlText,
%                 [{'ResLineCode',1},
%                  {'ReservationLine',1},
%                  {'ReservationLines',6},
%                  {'MakeBookingWithQuoteResult',1},
%                  {'MakeBookingWithQuoteResponse',1},
%                  {'soap:Body',1},
%                  {'soap:Envelope',1}],
%                 1,[],"C",text}],
%               [],"/home/dag-development/Documents/erlang/erlxml",undeclared},
%              {xmlElement,'ResLineDesc1','ResLineDesc1',[],
%               {xmlNamespace,'http://www.budget.co.za',
%                [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%                 {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%                 {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%               [{'ReservationLine',1},
%                {'ReservationLines',6},
%                {'MakeBookingWithQuoteResult',1},
%                {'MakeBookingWithQuoteResponse',1},
%                {'soap:Body',1},
%                {'soap:Envelope',1}],
%               2,[],
%               [{xmlText,
%                 [{'ResLineDesc1',2},
%                  {'ReservationLine',1},
%                  {'ReservationLines',6},
%                  {'MakeBookingWithQuoteResult',1},
%                  {'MakeBookingWithQuoteResponse',1},
%                  {'soap:Body',1},
%                  {'soap:Envelope',1}],
%                 1,[],"Fuel - Vehicle will be refueled at Renters cost",text}],
%               [],"/home/dag-development/Documents/erlang/erlxml",undeclared},
%              {xmlElement,'ResLineUnitChrg','ResLineUnitChrg',[],
%               {xmlNamespace,'http://www.budget.co.za',
%                [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%                 {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%                 {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%               [{'ReservationLine',1},
%                {'ReservationLines',6},
%                {'MakeBookingWithQuoteResult',1},
%                {'MakeBookingWithQuoteResponse',1},
%                {'soap:Body',1},
%                {'soap:Envelope',1}],
%               3,[],
%               [{xmlText,
%                 [{'ResLineUnitChrg',3},
%                  {'ReservationLine',1},
%                  {'ReservationLines',6},
%                  {'MakeBookingWithQuoteResult',1},
%                  {'MakeBookingWithQuoteResponse',1},
%                  {'soap:Body',1},
%                  {'soap:Envelope',1}],
%                 1,[],"0.00",text}],
%               [],"/home/dag-development/Documents/erlang/erlxml",undeclared},
%              {xmlElement,'ResLineChrgUnit','ResLineChrgUnit',[],
%               {xmlNamespace,'http://www.budget.co.za',
%                [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%                 {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%                 {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%               [{'ReservationLine',1},
%                {'ReservationLines',6},
%                {'MakeBookingWithQuoteResult',1},
%                {'MakeBookingWithQuoteResponse',1},
%                {'soap:Body',1},
%                {'soap:Envelope',1}],
%               4,[],[],[],"/home/dag-development/Documents/erlang/erlxml",
%               undeclared},
%              {xmlElement,'ResLineDesc2','ResLineDesc2',[],
%               {xmlNamespace,'http://www.budget.co.za',
%                [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%                 {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%                 {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%               [{'ReservationLine',1},
%                {'ReservationLines',6},
%                {'MakeBookingWithQuoteResult',1},
%                {'MakeBookingWithQuoteResponse',1},
%                {'soap:Body',1},
%                {'soap:Envelope',1}],
%               5,[],[],[],"/home/dag-development/Documents/erlang/erlxml",
%               undeclared},
%              {xmlElement,'ResLineChrg','ResLineChrg',[],
%               {xmlNamespace,'http://www.budget.co.za',
%                [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%                 {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%                 {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%               [{'ReservationLine',1},
%                {'ReservationLines',6},
%                {'MakeBookingWithQuoteResult',1},
%                {'MakeBookingWithQuoteResponse',1},
%                {'soap:Body',1},
%                {'soap:Envelope',1}],
%               6,[],
%               [{xmlText,
%                 [{'ResLineChrg',6},
%                  {'ReservationLine',1},
%                  {'ReservationLines',6},
%                  {'MakeBookingWithQuoteResult',1},
%                  {'MakeBookingWithQuoteResponse',1},
%                  {'soap:Body',1},
%                  {'soap:Envelope',1}],
%                 1,[],"0.00",text}],
%               [],"/home/dag-development/Documents/erlang/erlxml",undeclared},
%              {xmlElement,'ResLineNil','ResLineNil',[],
%               {xmlNamespace,'http://www.budget.co.za',
%                [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%                 {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%                 {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%               [{'ReservationLine',1},
%                {'ReservationLines',6},
%                {'MakeBookingWithQuoteResult',1},
%                {'MakeBookingWithQuoteResponse',1},
%                {'soap:Body',1},
%                {'soap:Envelope',1}],
%               7,[],[],[],"/home/dag-development/Documents/erlang/erlxml",
%               undeclared}],
%             [],"/home/dag-development/Documents/erlang/erlxml",undeclared}],
%           [],"/home/dag-development/Documents/erlang/erlxml",undeclared},
%          {xmlElement,'Errors','Errors',[],
%           {xmlNamespace,'http://www.budget.co.za',
%            [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%             {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%             {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%           [{'MakeBookingWithQuoteResult',1},
%            {'MakeBookingWithQuoteResponse',1},
%            {'soap:Body',1},
%            {'soap:Envelope',1}],
%           7,[],[],[],"/home/dag-development/Documents/erlang/erlxml",
%           undeclared},
%          {xmlElement,'RentalDuration5','RentalDuration5',[],
%           {xmlNamespace,'http://www.budget.co.za',
%            [{"soap",'http://www.w3.org/2003/05/soap-envelope'},
%             {"xsi",'http://www.w3.org/2001/XMLSchema-instance'},
%             {"xsd",'http://www.w3.org/2001/XMLSchema'}]},
%           [{'MakeBookingWithQuoteResult',1},
%            {'MakeBookingWithQuoteResponse',1},
%            {'soap:Body',1},
%            {'soap:Envelope',1}],
%           8,[],
%           [{xmlText,
%             [{'RentalDuration5',8},
%              {'MakeBookingWithQuoteResult',1},
%              {'MakeBookingWithQuoteResponse',1},
%              {'soap:Body',1},
%              {'soap:Envelope',1}],
%             1,[],"1",text}],
%           [],"/home/dag-development/Documents/erlang/erlxml",undeclared}],
%         [],"/home/dag-development/Documents/erlang/erlxml",undeclared}],
%       [],"/home/dag-development/Documents/erlang/erlxml",undeclared}],
%     [],"/home/dag-development/Documents/erlang/erlxml",undeclared}],
%   [],"/home/dag-development/Documents/erlang/erlxml",undeclared}
