language: erlang
otp_release:
  - 22.0
  - 21.3.8
  - 21.2
  - 21.1
  - 21.0
  - 20.3
  - 20.1
  - 20.0

before_install:
 - "chmod +x bootstrap_travis.sh"
 - "./bootstrap_travis.sh"

install:
  - "./rebar3 compile"
  
script:  
  - "./rebar3 eunit"